#include <winsock2.h>
#include <windows.h>
#include <wininet.h>
#include <process.h>
#include <commctrl.h>
#include <cstdio>
#include <shellapi.h>
#include <string>
#include <vector>
#include <tchar.h>
#include <memory>
#include <functional>
#include <DbgHelp.h>
#include <thread>
#include <span>
#include <mutex>
#include <map>
#include <MinHook.h>
#include <winternl.h>
#include <filesystem>